# sys
export GPG_TTY=$(tty)
export EDITOR=nvim
export VISUAL=code

export LC_ALL=
export LANG="zh_CN.UTF-8"
export LC_TIME="zh_CN.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_COLLATE="zh_CN.UTF-8"
export LC_NUMERIC="zh_CN.UTF-8"
export LC_MESSAGES="zh_CN.UTF-8"
export LC_MONETARY="zh_CN.UTF-8"
# sys end

# homebrew
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.ustc.edu.cn/brew.git"
export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.ustc.edu.cn/homebrew-core.git"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles"
export HOMEBREW_API_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles/api"
export HOMEBREW_NO_AUTO_UPDATE=true

export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
# homebrew end

# go
export PATH="${HOME}/go/bin:$PATH"
export GO111MODULE=on
# go end

# fzf
export FZF_DEFAULT_COMMAND="fd -H -t f -t d --exclude={.git,.idea,.vscode,.sass-cache,node_modules,build}"
export FZF_DEFAULT_OPTS="--height 40% --border --preview '(highlight -O ansi {} || cat {}) 2> /dev/null | head -50'"
# fzf end

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# nvm end

# gvm
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"
# gvm end

[[ -f ~/.alias ]] && source ~/.alias

export PATH="${HOME}/.local/bin:$PATH"

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

# antigen
source "$HOME/.antigen.zsh"
antigen bundle zsh-users/zsh-autosuggestions
antigen apply
# antigen  end