LEFT seek -10
RIGHT seek +10

UP add volume 5
DOWN add volume -5

ENTER cycle fullscreen

, playlist-prev
. playlist-next

- add speed -0.5
= add speed 0.5

# Mouse click toggle play/pause
MBTN_LEFT cycle pause