[general]
import = ["./theme/Gruvbox_Dark.toml"]
working_directory = "/Users/mdvis/Code"

[env]
TERM = "xterm-256color"

[font.normal]
family = "SSS"
style = "Regular"

[font]
size = 14.0

[terminal.shell]
program = "/Users/mdvis/.local/bin/tmux"

[cursor]
style = "Beam"